sc_allcreature_createbefore()
image_xscale=-1
hp=300
sc_allcreature_createafter()
timer=400
image_xscale=-1
hp=300
spawn=o_goblin_E
spawnonce1=0
layer_="medium_creature"
layer__="small_creature"
spawn1=0
spawnonce=0
spawnonce2=0